### ISSUE TITLE
Regression in v5.43.0

### ISSUE THREAD

**Issue by rhuanbarreto** [pulumi/pulumi-azuread#525]
### What happened?

After upgrade from 5.42.0 to 5.43.0 my code stopped working when doing Application.get():

```
Diagnostics:
  pulumi:pulumi:Stack (python-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/rhuan/code/python/infra/__main__.py", line 2, in <module>
        from functions.function import Permissions, function_deploy
      File "/Users/rhuan/code/python/infra/functions/function.py", line 34, in <module>
        from common_infra.app_registration import client_id, tenant_id
      File "/Users/rhuan/code/python/infra/common_infra/app_registration.py", line 6, in <module>
        app = Application.get("app-registration", object_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/rhuan/code/python/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/pulumi_azuread/application.py", line 1934, in get
        return Application(resource_name, opts=opts, __props__=__props__)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/rhuan/code/python/dist/export/python/virtualenvs/python-default/3.11.6/lib/python3.11/site-packages/pulumi_azuread/application.py", line 1693, in __init__
        ApplicationArgs._configure(_setter, **kwargs)
    TypeError: ApplicationArgs._configure() missing 1 required positional argument: 'display_name'
```

### Example

```python
from pulumi_azuread import Application
object_id="something"
app = Application.get("app-registration", object_id)
```

### Output of `pulumi about`

```
CLI          
Version      3.90.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.14.0
azuread       5.43.0
python        3.11.6
random        4.14.0

Host     
OS       darwin
Version  14.0
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
It looks like it's tracked in https://github.com/pulumi/pulumi/issues/14418

**Comment by justinvp** [comment]
I think this issue is actually different than https://github.com/pulumi/pulumi/issues/14418.

The example is calling:

https://github.com/pulumi/pulumi-azuread/blob/41675f1d9ab6097b9a40e6ddede87183045bcd28/sdk/python/pulumi_azuread/application.py#L1804

Which calls the `__init__` like:

https://github.com/pulumi/pulumi-azuread/blob/41675f1d9ab6097b9a40e6ddede87183045bcd28/sdk/python/pulumi_azuread/application.py#L1934

Which is this:

https://github.com/pulumi/pulumi-azuread/blob/41675f1d9ab6097b9a40e6ddede87183045bcd28/sdk/python/pulumi_azuread/application.py#L1685-L1694

The call to `_configure` here:

https://github.com/pulumi/pulumi-azuread/blob/41675f1d9ab6097b9a40e6ddede87183045bcd28/sdk/python/pulumi_azuread/application.py#L1693C13-L1693C58

Isn't taking into account that this is for a `.get` and the props are being passed in `__props__`.

In any case, https://github.com/pulumi/pulumi/pull/14427 has reverted the change that introduced `_configure` in the first place, which was released in v3.91.1. Once `pulumi-azuread` is updated to use the v3.91.1 codegen and a new version is released, this shouldn't be an issue.
